# Victor Rene Pérez Mayen.
## 19005180

## TAREA TEÓRICA No.3

In [2]:
import numpy as np

## 1. np.matrix

Obtiene una matriz de respuesta en base a un objeto tipo array, o de un string de datos. Este método está próximo a dejar de usarse según la referencia.

Ref: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [3]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [4]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

## 2. np.ndarray  

Un objeto tipo array representa un arreglo homogeneo y multidimensional. Un objeto asociado a un tipo de dato describe el formato de cada elemento en el arreglo, los arreglos deben ser estructurados usando array, zeros, empty, los parámetros se refieren a un método de bajo nivel. 

Ref: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

In [5]:
np.ndarray(shape=(2,2), dtype=float, order='F')

array([[8.69810959e-312, 1.33511562e-306],
       [1.60220936e-306, 6.23040373e-307]])

In [6]:
np.ndarray((2,), buffer=np.array([1,2,3]), offset=np.int_().itemsize, dtype=int)

array([2, 3])

Por lo que se especifica, el ndarray es un arreglo de n dimensiones, por lo que es un contenedor multidimensional de elementos del mismo tipo y tamaño. El número de dimensiones y de elementos en este arreglo es definido por la función "shape", el cual es una tupla con rangos que determinar los tamaños de sus dimensiones. 

Ref: https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)

numpy.ndarray

In [10]:
x.shape

(2, 3)

In [9]:
x.dtype

dtype('int32')

### La principal diferencia entre np.matrix y np.ndarray es que la función np.matrix únicamente trabaja con matrices, mientras que la función np.ndarray trabaja con tensores de N dimensiones en general.